### PR TITLE
Fix ResourceWarning warnings

### PR DESCRIPTION
**Pull request by haypo**
- RepositoryFactory.open(): close the stream after reading its
  content
- Repository._next_stream(): use "with" to close the next-stream file

### CODE REVIEW

**Comment by haypo** [comment]
Hum, it looks like Travis still runs tests on Python 3.2, but empty_fill = u'∙' in pip/_vendor/progress/bar.py raises a SyntaxError. It's time to stop running tests on Python 3.2, no?

**Comment by mtreinish** [comment]
I pushed: https://github.com/testing-cabal/testrepository/pull/28 to remove py3.2 testing from travis

**Comment by haypo** [comment]
The change to remove Python 3.2 from Travis has been removed. I rebased my change.

**Comment by haypo** [comment]
@rbtcollins & @freeekanayaka: would you mind to review this straighforward change? Travis CI is now happy (before, it only failed because of Python 3.2).

**Comment by haypo** [comment]
FYI this pull request doesn't fix *all* ResourceWarning warnings, but first the most obvious warnings. It helps to debug the remaining ones ;-)

**Comment by haypo** [comment]
Ping @freeekanayaka ? Can you please review this pull request?

**Comment by haypo** [comment]
Ping?

**Comment by thomir** [comment]
LGTM

**Comment by haypo** [comment]
Thank you!

I only fixed the most obvious issues, there are still a few remaining ResourceWarning, more tricky to fix. But it should now be easier to catch them.

**Pull request merged**
