### PR TITLE
Drop support for Python 2 name of configparser

### PR DESCRIPTION
**Pull request by jelmer**
Drop support for Python 2 name of configparser

This also removes the need for the extras module

### CODE REVIEW

**Comment by kajinamit** [comment]
@jelmer Hi. Thanks for this change. I'm wondering if I can request a new release so that we can consume this by pip installation.

**Comment by jelmer** [comment]
Yeah, I'll see if I can work out how to do a release. I don't think anybody but @rbtcollins has done any so far.

**Comment by rbtcollins** [comment]
`make release`

**Comment by kajinamit** [comment]
@jelmer wondering if you've got chance to try https://github.com/testing-cabal/testrepository/pull/49#issuecomment-1823133034 ?

**Comment by jelmer** [comment]
> @jelmer wondering if you've got chance to try [#49 (comment)](https://github.com/testing-cabal/testrepository/pull/49#issuecomment-1823133034) ?

I'm not a maintainer on pypi so there's no point in me doing that.

**Comment by kajinamit** [comment]
@rbtcollins Hi. May I ask you to create a release in case you get a chance ? It's greatly appeciated because we can get rid of extras from OpenStack's dependencies.

**Comment by rbtcollins** [comment]
I've added @jelmer as an owner on pypi

**Comment by jelmer** [comment]
> I've added @jelmer as an owner on pypi

Thanks! I'll see if I can do a release this week

**Comment by kajinamit** [comment]
Thank you both ! I now see 0.0.21  which was release yesterday.

**Pull request merged**
